Multilanguage support
codex-team/codex.special pull request #1
Opened 2016-09-24 17:38 UTC by talyguryn

- [ ] @neSpecc

2016-09-24 18:10 UTC, neSpecc commented on codex-special.v.1.0.js
> +        'ru' : {
у ключей не нужны кавычки

2016-09-24 18:11 UTC, neSpecc commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
var

2016-09-24 18:11 UTC, neSpecc requested changes

2016-09-24 18:13 UTC, talyguryn commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
не нужен. я texts создаю на строке 143

2016-09-24 18:18 UTC, talyguryn commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
пардон. на строке 26

2016-09-25 12:30 UTC, neSpecc commented on codex-special.v.1.0.js
> +    var texts = null;
а зачем эта переменная? уже же есть DICT

2016-09-25 12:31 UTC, neSpecc requested changes

2016-09-25 12:31 UTC, neSpecc commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
а зачем

2016-09-25 12:31 UTC, neSpecc commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
я бы это делал только в той функции, где вызываются тексты

2016-09-25 13:04 UTC, talyguryn commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
таких функций три
разве не лучше задать тексты один раз и не вспоминать о них?

2016-09-25 13:06 UTC, neSpecc commented on codex-special.v.1.0.js
> +        texts = DICT[initialSettings.lang];
ладно

2016-09-25 13:06 UTC, neSpecc approved these changes

2016-09-25 13:07 UTC, merged