Fast position feature
codex-team/codex.special pull request #11
Opened 2016-12-06 23:22 UTC by talyguryn

thx @n0str

2016-12-06 23:24 UTC, neSpecc requested changes

2016-12-06 23:24 UTC, neSpecc commented on codex-special.v.1.0.js
> +    var CSS_FILE_PATH = 'codex-special.v.1.0.css';
подключать надо min

2016-12-06 23:34 UTC, talyguryn commented on codex-special.v.1.0.js
> +    var CSS_FILE_PATH = 'codex-special.v.1.0.css';
чтобы подключить мин, надо обновить ещё и мин.

если всё устраивает, то следующим коммитом залетают сжатые версии и вопрос решен

2016-12-07 09:04 UTC, neSpecc requested changes

2016-12-07 09:04 UTC, neSpecc commented on codex-special.v.1.0.js
> +    var CSS_FILE_PATH = 'codex-special.v.1.0.css';
да, и min.js тоже нужен. А еще нужно минорную версию обновить. И в readme написать о новой фиче.

2016-12-07 09:04 UTC, neSpecc commented on codex-special.v.1.0.css
> +    top: 0 !important;
а зачем все эти important? 
лучше позицию вынести в модификаторы.

К тому же, сейчас на мобильной версии тулбар крепится к нижней части экрана. Как этот вопрос решен с новыми позициями?

2016-12-07 09:04 UTC, neSpecc commented on codex-special.v.1.0.js
> +                case 'top-left': nodes.toolbar.classList.add('codex-special__position_top', 'codex-special__position_left'); break;
по бэму будет `codex-special__toolbar_top`, правда эту кашу хочется как-то более изящно написать, может вынести  `nodes.toolbar.classList.add` из ифа?

2016-12-07 09:51 UTC, talyguryn commented on codex-special.v.1.0.js
> +    var CSS_FILE_PATH = 'codex-special.v.1.0.css';
не переживай, успею обновить сжатые скрипты

2016-12-07 10:08 UTC, talyguryn commented on codex-special.v.1.0.css
> +    top: 0 !important;
да, important лишние, уберу

2016-12-07 10:08 UTC, talyguryn commented on codex-special.v.1.0.css
> +    top: 0 !important;
никак. всё так же внизу

2016-12-13 18:21 UTC, n0str approved these changes

2016-12-13 20:48 UTC, neSpecc approved these changes

2016-12-13 20:48 UTC, merged